language: android
dist: trusty
jdk: openjdk9
android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'
before_install:
  - chmod +x gradlew
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - ./gradlew check
  # cat MIDIDriver/build/outputs/lint-results.xml
  - cd ./MIDIDriver && mvn install -DskipTests=true -Dandroid.sdk.path=$ANDROID_HOME
